endpoint: "https://api.testnet.solana.com"
pubkeys:
  - "83astBRguLMdt2h5U1Tpdq5tjFoJ6noeGwaY3mDLVcri"
  - "--Ac4R6EFdjkNaVBoUk4T26XrGmdhQTdHcwpswCqopfbS6"
  - "FT9QgTVo375TgDAQusTgpsfXqTosCJLfrBpoVdcbnhtS"
